### ISSUE TITLE
Sticky holiday div has a scroll bar bug

### ISSUE THREAD

**Issue by berke-volkan** [hackclub/high-seas#1014]
https://cloud-g2tvbsrsi-hack-club-bot.vercel.app/01000025949.mp4

**Comment by Gitstar-OC** [comment]
Might be an error working fine on my device. 
 ![Image](https://github.com/user-attachments/assets/c27697cd-4997-44fd-b85d-864f7069e994)

**Comment by Gitstar-OC** [comment]
Closing this as it is working could you please provide some more details so that I can reproduce it  ?

**Comment by Gitstar-OC** [comment]
Also it is being fixed now with the new display method. 

![Image](https://github.com/user-attachments/assets/971bdd49-4dd9-4a74-814f-fa336bc399b7)
