### ISSUE TITLE
Feedback is only shown on the original project and there is no change in it after an update.

### ISSUE THREAD

**Issue by Gitstar-OC** [hackclub/high-seas#1034]
@polytroper the feedback is a great thing that we have implemented however I think that is not chaning after an update regarding it has been shipped. I have shipped update to 2 of my projects today after working on the feedback and I think the feedback still remains the same.

**Comment by BudzioT** [comment]
We grab everything including title, links from the root ship - this mean that edits don't work too. For this I have already made an PR, but will include the feedback too into it
