### ISSUE TITLE
Other people including me have received doubloons for project before even voting

### ISSUE THREAD

**Issue by Gitstar-OC** [hackclub/high-seas#1035]
![Image](https://github.com/user-attachments/assets/f1cc68d7-840a-446f-81e2-b45fb5e093d6)

It still shows this while I have got some doubloons for my projects that I have updaed. 

This has been reported by @PonderSlime before a month [here](https://hackclub.slack.com/archives/C0806N83T99/p1732675118203059) and I thought it was fixed.

**Comment by BudzioT** [comment]
It doesn't work like you think. It will only work on the next project, it won't even go into matchups - this is on the airtable side

**Comment by PonderSlime** [comment]
@BudzioT i encountered a similar issue. If i submit a project, don't vote, and submit another one, the first one will be immediately payed out. The votes are simply stacked onto the latest project.

So, if you were to submit three, two would be payed out, and you would have to vote 36 times to get the third one to pay out

**Comment by Gitstar-OC** [comment]
Woh, so if I ship a minor one hour project at last it will pay you all of the complete previous hours and projects that you have worked on. I found it now so I just wonder if someone has used it. @BudzioT in the database is there a way to see how many votes of a person are remaining or not ? If not you might need to create one after this!!

**Comment by BudzioT** [comment]
I will check it out, we have a field in airtable to check for balance of votes, but will try to debug

**Comment by BudzioT** [comment]
Can someone give me exact steps to recreate it? Either I'm a dum-dum or it doesn't work for me ; (. I have shipped 3 projects either at once or with some delays and only the first one goes into matchups, the rest of them aren't eligible for them

**Comment by PonderSlime** [comment]
with 3 projects submitted, i notice that the first two would get a payout

**Comment by PonderSlime** [comment]
all 3 entered the wonderdome

**Comment by BudzioT** [comment]
It does however seem to take your vote balance into play from what I see... it seems like it was correct (two projects got payout cause of vote balance and the third one - cause it was the one that brought your vote balance to negatives, meaning your 4th ship wouldn't go into matchups),
Mind recreating that on some dummy projects if you think it doesn't work though? You have currently vote balance equal to 0 @PonderSlime . I can delete these projects after

**Comment by Gitstar-OC** [comment]
I might be able to do that, should I do it. I have some time on some projects though I guess.

**Comment by Gitstar-OC** [comment]
The issue is fixed and the ships does not go into wonderdome unless you have voted 12 times, which @PonderSlime you did (10 votes) so your second ship got into wonderdome and the third one did not. 

We tried reproducing this and turns out that it's resolved!
