### ISSUE TITLE
Voting interface should show if a project is an update

### ISSUE THREAD

**Issue by maxwofford** [hackclub/high-seas#134]
![Screenshot 2024-10-17 at 4 33 25 PM](https://github.com/user-attachments/assets/3189633f-47eb-4e07-9d56-e556fb60ae65)

This view should show if a project is an update (maybe one of the pills) and I should be able to read the "update description" that the submitter wrote about the project!

**Comment by cskartikey** [comment]
Sorry for the delay. #796 fixed this
