### ISSUE TITLE
Slack profile info for creator of each ship in battles

### ISSUE THREAD

**Issue by polytroper** [hackclub/high-seas#241]
Battles should include a link to the slack profile of the authors of the projects shown, and possibly a slack PFP.

We need to be careful to do this in a way that does not introduce biases into the voting. We may also need to give authors the ability to choose if they want to be contactable in this way, due to potential concerns like harassment of girls.

I would consider this to be a low-priority issue until we have had a real discussion about the concerns above, especially since the platform can run fine without it.

**Comment by maxwofford** [comment]
Cutting this because people will vote for their friends
