### ISSUE TITLE
Advanced voting analytics/telemetry

### ISSUE THREAD

**Issue by polytroper** [hackclub/high-seas#242]
We need a lot more data to _really_ be able to tell if people are fudging votes, including:
* How long did they spend on the vote in total?
* Did they open the deploy links? How long after opening each deploy link before they interacted with something else on the page?
* Did they open the readmes? How long did they spend looking at each one?
* Did they open the repos? How long after opening each repo before they interacted with something else on the page?
* How long did it take for them to type out their explanation?
* Did they do any deletions in their explanation?

We will need to have a discussion about how to store all this data in a way that makes it analyzable (since the structure of battle records makes it difficult to store and analyze data on each battle separately), and does not put excessive pressure on airtable request rate limits or balloon the number of records in the main high seas base.

We also cannot sign most of this data since it is generated purely by the user, which means it ideally would be transmitted real-time, event-by-event, rather than in a blob upon vote submission so that it is not easily spoofed.

Do we just want to use an off-the-shelf analytics library for this purpose? If so, we need to take care not to be thwarted by anti-tracking extensions.

Tagging @maxwofford because he probably has useful thoughts here.

Basic MVP analytics/telemetry is outlined in [issue 243](https://github.com/hackclub/high-seas/issues/243)

**Comment by maxwofford** [comment]
Closing as stale
