### ISSUE TITLE
Livestream watch party

### ISSUE THREAD

**Issue by polytroper** [hackclub/high-seas#273]
We need a watch party for the github keynote for people in slack. They should not be told what is going to happen beforehand, just that they should RSVP for this event to watch the keynote at this time. Acon will be launching High Seas on stage. We want high energy and good vibes around this!

Event and RSVP flow should be on events.hackclub.com

The day 2 keynote is on October 30th at 9:00–9:45am pacific time. We are the final part of the keynote, roughly the last 5–10 minutes, so we will need to keep people engaged and keep energy up for the first 35–40 minutes when there is no Hack Club content. Arpan, please comment with some strategies for this

**Comment by maxwofford** [comment]
Done!
