### ISSUE TITLE
Redirect user to the tutorial (current step if possible, start if not) if they leave and then go back to highseas.hackclub.com before completing tutorial

### ISSUE THREAD

**Issue by polytroper** [hackclub/high-seas#443]
@transcental started the tutorial, then left and went back to the marketing page, and clicked "enter the harbor". It brought them to the signpost with no tutorial. Same browser session, cookies were intact. Needs to redirect the user back to the page/step they were at.

**Comment by maxwofford** [comment]
This is fixed!
