### ISSUE TITLE
Improve logging in Hakatime setup script

### ISSUE THREAD

**Issue by cytronicoder** [hackclub/high-seas#559]
The current setup script would benefit from adding more descriptive error messages based on what we noticed as common errors, capturing command outputs for troubleshooting, and providing detailed logs during each setup phase. A verbose mode could be helpful. Including specific suggestions based on HTTP response codes for failed heartbeats and ensuring visibility into any VS Code extension installation issues would significantly improve usability.

**Comment by maxwofford** [comment]
What's the status of this @cytronicoder? I'm closing as stale and you can reopen if it's needed

**Comment by cytronicoder** [comment]
@maxwofford I need to test the new script a bit but we can probably merge afterwards! No need to reopen - it's almost polished
