### ISSUE TITLE
Tutorial didn't resume when directed to Wonderdome

### ISSUE THREAD

**Issue by polypixeldev** [hackclub/high-seas#589]
I was going through the tutorial, but when I got to the Wonderdome the tutorial didn't reappear. I started voting for projects since I assumed that's what I was supposed to do, but didn't know how many I needed to vote for to complete the tutorial. Also, the example vote reason was still autofilling for these votes. However, when I went to the signpost, it redirected me back to the Wonderdome, and then the tutorial reappeared.

**Comment by maxwofford** [comment]
Closing as fixed– will reopen if we get more reports of it
