### ISSUE TITLE
Tutorial Glitch

### ISSUE THREAD

**Issue by transcental** [hackclub/high-seas#592]
The tutorial seems to bug out when you attempt to type anything in the fields during the example shipping, if I'm right abt that I think the field should be locked since its autofilled in the tutorial.

---

_This issue was created automatically by the support team. See the appropriate thread [here](https://hackclub.slack.com/archives/C07PZNMBPBN/p1730411122.301029)_

**Comment by maxwofford** [comment]
Closing as fixed– will reopen if we get more reports of it!
