### ISSUE TITLE
security: token leaks

### ISSUE THREAD

**Issue by kcoderhtml** [hackclub/high-seas#608]
We have two token leaks that need to be changed: see [this thread](https://hackclub.slack.com/archives/C07MS92E0J3/p1730560910090669) for more details

![Image](https://github.com/user-attachments/assets/b8ea15b2-a79b-4c08-b66b-3d898abb686c)

**Comment by maxwofford** [comment]
These were rotated! They're still in the commits though if anyone wants to go on an easter-egg hunt though ;-p
