### ISSUE TITLE
Pressing `ESC` in Tutorial Causes Buggy State

### ISSUE THREAD

**Issue by transcental** [hackclub/high-seas#673]
^ literally what the op of the thread said

Did not repo, too lazy to go make a new google ACC and go thru the tutorial to press the esc key :/

---

_This issue was created automatically by the support team. See the appropriate thread [here](https://hackclub.slack.com/archives/C07PZNMBPBN/p1730936740.625539)_

**Comment by maxwofford** [comment]
This is still true, but if you refresh the page things restore correctly.
