### ISSUE TITLE
Arrpheus should handle existing MCG users

### ISSUE THREAD

**Issue by polytroper** [hackclub/high-seas#724]
Right now we are getting a huge number of existing MCG users signing up for High Seas through the homepage form. When Arrpheus fails with `already_in_team`, it needs to check if that user is MCG. If so, it needs to set the `preexisting_multi_channel_guest` field in airtable, create a magic token for them, add them to all the high seas channels, and then DM that user their magic auth message (through Arrpheus, not slackbot, since existing users do not open automatically to slackbot).

**Comment by rivques** [comment]
Fixed! (though I had to use an undocumented endpoint to invite MCGs to new channels for some reason)
