### ISSUE TITLE
Tutorial is bricked!

### ISSUE THREAD

**Issue by cskartikey** [hackclub/high-seas#732]
Looks like we're setting local cookies first before getting tutorial completed thing from airtable. So yes, it's bricked.

**Comment by maxwofford** [comment]
I don't understand this ticket @cskartikey, can you clarify and include screenshots or recordings? is this on new accounts or existing ones?

**Comment by maxwofford** [comment]
I just went through the tutorial top to bottom in production and got through it with a new account and verification:

![Image](https://github.com/user-attachments/assets/8019d4ab-86c0-47cb-99aa-e9ab392c19a3)
![Image](https://github.com/user-attachments/assets/dbb42e4d-b34c-49a8-aa3b-ebe0a1838b13)

**Comment by cskartikey** [comment]
Clear your cookies on your existing account and try to login

**Comment by maxwofford** [comment]
![Image](https://github.com/user-attachments/assets/cff0d575-3d5c-425c-be08-3e6b8dd53989)
I just cleared cookies and signed in on my main account. Worked fine. What should I expect to see?

**Comment by cskartikey** [comment]
It just fixed itself

**Comment by maxwofford** [comment]
Now the tutorial is starting, but the projects list is empty![Image](https://github.com/user-attachments/assets/efeae649-5443-40a6-a8d6-8c2db36b791f)

**Comment by cskartikey** [comment]
Project list is not empty for me but it shows my hackatime project

**Comment by maxwofford** [comment]
@malted I'm closing this due to the fix today!
