### ISSUE TITLE
Make High Seas Slack invites expire on Jan 31st

### ISSUE THREAD

**Issue by transcental** [hackclub/high-seas#743]
There are so many users who joined after Arcade ended using their Arcade invites. Can we set the High Seas invites to expire when High Seas ends so we don't have this issue again?

**Comment by rivques** [comment]
I don't see a way to do this, even in the undocumented API - is there something I'm missing?

**Comment by rivques** [comment]
oh yep, just found it! for some reason it only appears when you're inviting someone as a guest

implementing now...

**Comment by rivques** [comment]
so it looks like this actually doesn't quite do what I think it does - this sets the date that the account that joins will be deactivated, not the date the invite will stop working. I don't think that's what we want to do, right?

(here's the invite email that this sends:)
![Image](https://github.com/user-attachments/assets/8af7f386-b2d0-4f57-8354-a140ea2ba4fd)

**Comment by transcental** [comment]
Oh oops! Nevermind then, I misread that  :/
I'm guessing that it wouldn't deactivate if they get promoted to a full member and whilst not having MCG's would be nice, it would cause a lot more headaches later down the line. (People being deactivated and needing to be manually reactivated in future events - whereas with MCG's we can make a script to convert the accounts like you did for Arcade ones)
