### ISSUE TITLE
Block submission of update / projects that are <1 hr

### ISSUE THREAD

**Issue by maxwofford** [hackclub/high-seas#760]
This was intended from the start because the matchup generator doesn't create matchups from sub- 1 hour projects, but looks like we missed this!

**Comment by YetAnotherNotHacking** [comment]
https://github.com/hackclub/high-seas/issues/763#issuecomment-2479993464

Can confirm, seems to cause a negative vote issue!

**Comment by BudzioT** [comment]
Fixed and merged a few days before
