### ISSUE TITLE
problem in time tracking

### ISSUE THREAD

**Issue by kokojkj** [hackclub/high-seas#764]
when i make new file not in folder 
in make time in "unknown"
no problem 
but when i ship and do new project not in folder i dont find (unknown again with my time )
but when i remove old ship i find "unknown" again when more time added
why this ?

**Comment by NeonGamerBot-QK** [comment]
this seems like a hacktime issue;
a fix is probably coding in a folder.

**Comment by polytroper** [comment]
Yeah, you gotta work in a folder. That is just how hackatime tracks projects.
