### ISSUE TITLE
Projects are still getting in wonderdome after 10 votes are complete

### ISSUE THREAD

**Issue by Gitstar-OC** [hackclub/high-seas#784]
So this is a story of my project for which I got payout and 10 votes near about a week before and someone today on slack sent me a screenshot that you have made a great project and told me that he has voted for my project today. How is that possible maybe is this a reason people are getting less payout. He also as the screenshot taken.

**Comment by Gitstar-OC** [comment]
Note: I don't know if we send project after 10 votes are completed or not, please correct me!

**Comment by felixgao-0** [comment]
Intended feature

**Comment by transcental** [comment]
This isn't a bug, we need the data from those projects to accurately payout projects
