### ISSUE TITLE
User Suggestion: Ongoing Votes

### ISSUE THREAD

**Issue by transcental** [hackclub/high-seas#788]
Could votes be ongoing? Like new projects are given top priority, but like for every 5 new projects, the person gets to vote on 2 old projects. If you get 10 votes on your old project, you get 1 doubloon

---

_This issue was created automatically by the support team. See the appropriate thread [here](https://hackclub.slack.com/archives/C07PZNMBPBN/p1731729799.643279)_

**Comment by polytroper** [comment]
Votes are ongoing, old projects show up in every matchup (new projects are never matched against each other). But no we cannot pay out additional doubloons based on those votes
