### ISSUE TITLE
Hovering anywhere over Y-Axis of referall button shows referall explanation

### ISSUE THREAD

**Issue by BudzioT** [hackclub/high-seas#793]
You can hover anywhere on the Y-axis of referall button to show explanation
![Image](https://github.com/user-attachments/assets/9c605c56-81df-4e0e-8fdc-83efbbc86f1f)

**Comment by Gitstar-OC** [comment]
Well I think that is because the hovering property is added to the complete div. 

![Image](https://github.com/user-attachments/assets/74f5b29f-b696-4907-a30b-625af41f5641)

Will solve it with a pr if possible.

**Comment by Gitstar-OC** [comment]
#809 will solve the issue.
