### ISSUE TITLE
Unjust pirates curse

### ISSUE THREAD

**Issue by YetAnotherNotHacking** [hackclub/high-seas#799]
When voting, I was looking at each project's demo and voting fairly. I have voted about 20 more times after it writing essays about which on is better and pirates curse is still there. I just shipped 12 hours of work and if I get half payout for it, it will be really really really annoying.

It says my votes were flagged

I wrote about 2 sentances about why it is technical or creative when voting for them and then tab+enter to go to next one 

I type about 120 wpm if that might trigger something

this is on my account registered under yetanotherdingus@gmail.com

I just want me points, IDK why I was flagged and I cannot seem to get unflagged and I almost have enough points to get a payout, which is going to get halved :(

**Comment by YetAnotherNotHacking** [comment]
Real question here, more information abuot why you got a curse, it just says my votes were bad (I personnaly dissagree) and it is unfair that I did not get a warning, just taking away a lot of my points from my reward because of something I thought I was completing with a satisfactory quality.

**Comment by YetAnotherNotHacking** [comment]
I was able to complete about 25 votes to undo it, but there should be a bit more information about what exactly triggered it. I did everything quite well in my opinion.

**Comment by polytroper** [comment]
What is your @ tag on slack, so I can look into what tripped the algo for you?

**Comment by YetAnotherNotHacking** [comment]
Sure, @_Dread

**Comment by polytroper** [comment]
Seems like your votes diverged enough from the consensus that it flagged them as statistically random. I made some adjustments to the algorithm but I would still overall encourage you to put more careful thought into voting, it's fairly unlikely for one person's judgments to get flagged like that unless they're being a bit hasty ;)

**Comment by vortexprime24** [comment]
@polytroper I'm sorry for doing like 5 votes with same reason....I type on 60+ wpm (80 average) too, but I was trying to do votes quick and repeated the copied reason....sadly, I'm now infected!

I have been voting from the last 30mins with fair reasons and after watching demos but the effect hasn't still removed from my account.

aasheeshsaumya@gmail.com
Slack Member ID U084JNL5MPT
