### ISSUE TITLE
When shipping, also fill out YSWS details

### ISSUE THREAD

**Issue by maxwofford** [hackclub/high-seas#806]
![Image](https://github.com/user-attachments/assets/db1576f5-3ce6-4d08-8cdf-8e7cd8eafff3)

We have a single-select field on ships called "for_ysws". I've been manually setting this for every incoming submission but I'd love to have users fill this out when they submit!

Here are the options, with a few caveats below:

![Image](https://github.com/user-attachments/assets/d2ecc0c2-e69f-4c0c-89dd-1a8c3f2fdf81)
![Image](https://github.com/user-attachments/assets/0691219f-bbad-4d1e-b337-d7925351d03c)
![Image](https://github.com/user-attachments/assets/f17b349b-ea3f-4f3d-b364-3e0a0614571f)

That said, "high seas", "low skies", and "none" should all be hidden. The first option selectable (and the default selected) should say "none", but actually set the field to blank on submission. This will show up in my filters as something I have to manually categorize. To reiterate, there should be no way for the user to set those 3 options themselves in the db.

This should also be hidden while going through the tutorial! No point in confusing users.

**Comment by Gitstar-OC** [comment]
Is someone working on this ?

**Comment by Gitstar-OC** [comment]
@maxwofford I will need to understand more about what needs to be done, could you explain in Slack .

**Comment by BudzioT** [comment]
I already began and it's working (isn't disabled in tutorial yet) so I'm stealing this, sorry ; p

**Comment by Gitstar-OC** [comment]
No Problem :)

**Comment by BudzioT** [comment]
https://github.com/hackclub/high-seas/pull/923 done
