### ISSUE TITLE
Dino doesn't get disabled during use

### ISSUE THREAD

**Issue by matytyma** [hackclub/high-seas#808]
Dino can be clicked over and over again when "thinking", thus producing gibberish

**Comment by maxwofford** [comment]
@matytyma please include more details on your issues– screenshot and URL! which dino?

**Comment by matytyma** [comment]
This guy, located at root
![Image](https://github.com/user-attachments/assets/d32c5853-1558-4c1b-9002-de217b2afc20)

**Comment by Gitstar-OC** [comment]
I will **try to fix this** but I don't have openai api keys :(
