### ISSUE TITLE
People are allowed to submit 0 hours ships

### ISSUE THREAD

**Issue by transcental** [hackclub/high-seas#851]
You can submit ships that have 0 hours. I think we should make it to allow only ships >= 1 hour.

---

_This issue was created automatically by the support team. See the appropriate thread [here](https://hackclub.slack.com/archives/C07PZNMBPBN/p1732355627.498449)_

**Comment by Gitstar-OC** [comment]
Maybe I will try to work on this.

**Comment by TheSman122333** [comment]
I personally think it should be allowed, as people may have worked on projects beforehand, like me.

**Comment by BudzioT** [comment]
@TheSman122333 but they didn't log hours with Hackatime then, so it doesn't make too much sense, as payout remains 0

**Comment by TheSman122333** [comment]
Thats true

**Comment by polytroper** [comment]
Fixed
