### ISSUE TITLE
Should allow README's from outside of GitHub and stop assuming GitHub

### ISSUE THREAD

**Issue by uhidontkno** [hackclub/high-seas#853]
I understand that most would host their code on GitHub, but I host my code on GitLab. Every time I ship my project, I get a readme error because my readme is not hosted on GitHub. It also shows a GitHub logo, which is misleading because it's not on GitHub. 

I don't know Next.js but you should instead:
- Show icons based on Git Provider (github for github.com, gitlab for gitlab.com, codeberg for codeberg.org, forgejo for nest, etc)
- Allow any README.MD file to be displayed (as long as the mimetype is correct) instead of ones from GitHub.

<img src="https://github.com/user-attachments/assets/e3f814fa-17e8-4571-992d-72dae5f7efd9" width="400" align="center" />

**Comment by uhidontkno** [comment]
Also the doubloon display should be plural not singular

**Comment by Gitstar-OC** [comment]
Well here's the thing as you also know most of the hackclubbers host their code on github (99% +) it is better to use it as the singal alternative. I do not say that the other platforms are not useful but it will not be of any help for us to spend our time while fixing this. 
Maybe

**Comment by uhidontkno** [comment]
You could atleast just accept any URL going to a file with a
* `text/markdown`
* `text/x-markdown`
* `text/plain`
mimetype

**Comment by maxwofford** [comment]
@uhidontkno we def want to support gitlab (& all the other git hosts we can) for high seas! Thanks for flagging these issues.

Just submitted https://github.com/hackclub/high-seas/pull/857 for the pluralization stuff. Looking into those other things now!

**Comment by maxwofford** [comment]
Ok, the button text can easily be fixed– that was hard coded just to save time but we can pretty easily add in the other git hosts! As for the "Your git readme isn't loading" that actually looks correct. The help text doesn't help you here because it's showing the github instructions, but we aren't regexing the URL to make sure it's github or anything– we show it when the URL fails to load.

**Comment by maxwofford** [comment]
![Image](https://github.com/user-attachments/assets/7e3b6ad0-bc97-4a29-81d6-2481587dc646)

Ah, there it is! Gitlab doesn't like hotlinks to their raw URLs. Maybe host on #cdn in the slack?

**Comment by uhidontkno** [comment]
That explains why I'm getting the error. I thought you used `.startsWith` or something. Gonna use my CORS proxy or #cdn for future ships.

Nov 24, 2024 8:55:41 PM Max Wofford ***@***.***>:

**Comment by maxwofford** [comment]
Nah, we actually did build high seas with git{lab|ea} support but there are def some parts of the UI that are hardcoded to show GH because limited developer time. We'll totally accept PRs to polish up the experience though for our other public git host users, or even self-hosted gitserver users!

**Comment by maxwofford** [comment]
P.S. https://jhythm.rare1k.dev/mainmenu is sick! Love the UI's clickyness– I kinda want to add those sounds to the high seas UI

**Comment by uhidontkno** [comment]
Jhythm is on Itch.io too https://rare1k.itch.io/jhythm

Nov 24, 2024 9:06:46 PM Max Wofford ***@***.***>:

**Comment by uhidontkno** [comment]
Oh also, the sound button is behind all the UI stuff so you can't listen to the pirate tunes on mobile

**Comment by maxwofford** [comment]
@uhidontkno there are 77 open issues. If you want it fixed, you should submit a pull request!

**Comment by maxwofford** [comment]
Closed by https://github.com/hackclub/high-seas/pull/858!
