### ISSUE TITLE
Shipyard only accepts githubusercontent.com README urls

### ISSUE THREAD

**Issue by felixgao-0** [hackclub/high-seas#866]
Related ticket: https://hackclub.slack.com/archives/C07PZNMBPBN/p1732680687707819

URLs from services like codeberg aren't accepted as README links. It might work better to look for keywords like raw & README.md.

---

![Image](https://github.com/user-attachments/assets/47da91c2-e512-4ad1-89bb-76249699f59b)
the url: https://codeberg.org/stormyyy/nightfall/raw/branch/main/README.md

**Comment by NeonGamerBot-QK** [comment]
i can do this in a pr soon

**Comment by NeonGamerBot-QK** [comment]
Hi @felixgao-0 ! i checked the code and there is nothing wrong actually, its that codeberg uses COR's which is preventing high seas from loading the readme.
![Image](https://github.com/user-attachments/assets/2a08f5cf-ac16-4e36-83d8-6456187d4957)

**Comment by felixgao-0** [comment]
Nooooooo, tysm for looking into this anyways:)

**Comment by felixgao-0** [comment]
Marking closed (forgot to do so earlier) now
