### ISSUE TITLE
Wrong image links allowed

### ISSUE THREAD

**Issue by BudzioT** [hackclub/high-seas#899]
I'm not sure if we can call it an issue but:
- We allow base64 contents as screenshot URL, making shipyard crash for someone
- We also allow 32K image, it might make someone else crash, but didn't test it out

**Comment by NeonGamerBot-QK** [comment]
wdym by 32k image? like above a certain length?

**Comment by BudzioT** [comment]
32k resolution, saw it crashes some websites for some users/devices, not sure if it applies here. Also base64 contents make the user not able to go to shipyard anymore lol

**Comment by NeonGamerBot-QK** [comment]
i think i can make a fix for base64 urls; not so sure about 32k resolution..

**Comment by BudzioT** [comment]
Should be good, we don't wanna just people get soft-locked. Thanks

**Comment by Gitstar-OC** [comment]
Implementation of #903 might solve this issue.

**Comment by NeonGamerBot-QK** [comment]
Hi @Gitstar-OC this is already solved by the pr I have set up! #900 
You may setup a new PR to fix #903
