### ISSUE TITLE
Users allowed to submit a localhost URL as a project demo

### ISSUE THREAD

**Issue by JeffreyWangDev** [hackclub/high-seas#901]
The user gave a localhost url as a demo: https://hackclub.slack.com/archives/C07PZNMBPBN/p1733103195394949

I also saw the same project

**Comment by NeonGamerBot-QK** [comment]
ill pick this up rn!

**Comment by NeonGamerBot-QK** [comment]
sadly for the previous ships i cant fix... but i can give a list for any admin who wants to remove them!
https://hackclub.slack.com/archives/C07UA18MXBJ/p1731441859651479
https://hackclub.slack.com/archives/C07UA18MXBJ/p1732908308982629
https://hackclub.slack.com/archives/C07UA18MXBJ/p1732678133286899
https://hackclub.slack.com/archives/C07UA18MXBJ/p1731187330856639
https://hackclub.slack.com/archives/C07UA18MXBJ/p1733098883295689

**Comment by JeffreyWangDev** [comment]
I'm not sure that fixes it... You also have a lot of changes for something that is kinda small...
This should fix it
https://github.com/hackclub/high-seas/pull/902

**Comment by NeonGamerBot-QK** [comment]
> I'm not sure that fixes it... You also have a lot of changes for something that is kinda small... This should fix it [#902](https://github.com/hackclub/high-seas/pull/902)

wdym? its with another fix thats why there is other stuff and it fixes it?
@JeffreyWangDev
