### ISSUE TITLE
Website is getting slown down due to the new div in between

### ISSUE THREAD

**Issue by Gitstar-OC** [hackclub/high-seas#904]
https://github.com/user-attachments/assets/5defb287-ebf2-45b2-87ca-7267a157d262

The website is getting slowed down too much when user is clicking on get started, not a big issue though I think instead of showing the new div and creating it we should just show a popup or normal text.

**Comment by maxwofford** [comment]
This is probably a bug in the movement implementation! let's fix it!

**Comment by Gitstar-OC** [comment]
#924 will solve this.

**Comment by taciturnaxolotl** [comment]
just a note for next time: if you do `closes #904` on the pr then it will auto close the issue when the pr is merged :)
