### ISSUE TITLE
Improper Windows setup command

### ISSUE THREAD

**Issue by iamawatermelo** [hackclub/high-seas#908]
Use `Invoke-WebRequest -UseBasicParsing -Uri <setup script>`. By default, it uses the Internet Explorer engine to parse requests (no, I don't know why Microsoft thought that was a good idea). Someone on Windows Server Core (no, I don't know why they were on Windows Server Core) was having problems.

**Comment by SkyfallWasTaken** [comment]
I think it can just be `iwr-UseBasicParsing <setup script>`

**Comment by taciturnaxolotl** [comment]
Oh that is weird

**Comment by taciturnaxolotl** [comment]
Do you know who was affected by this? I'd like to test the new changes with them
