### ISSUE TITLE
Adding more Features.

### ISSUE THREAD

**Issue by sakshamwithweb** [hackclub/high-seas#911]
Adding one more optional text area for feedback for the developers on Wonder Doom will be great.

**Comment by Gitstar-OC** [comment]
Could you please elaborate what you mean by that and what will be the use of it ?

**Comment by sakshamwithweb** [comment]
A developer will always want to make its project excellence, that is why a textarea in wonderdoom for feedback of other developers(optional to fill)

**Comment by sakshamwithweb** [comment]
Ok Thanks!
