### ISSUE TITLE
Removing Framework 16 from the shop.

### ISSUE THREAD

**Issue by Gitstar-OC** [hackclub/high-seas#915]
As the only framework 16 has been gone I think we should remove it from the shop.

**Comment by Gitstar-OC** [comment]
@BudzioT   what do you think about it ?

**Comment by BudzioT** [comment]
No, we want to have a history of prizes like on Arcade - at least that what I think should be done. Just disabling buy button should be enough

**Comment by Gitstar-OC** [comment]
Hmm, that will be enough. Should I create a new pr for that ? Along with the text Oh this is gone now ? :)

**Comment by Gitstar-OC** [comment]
The line will be `we only had one of this, and it's gone now 🥲`

**Comment by BudzioT** [comment]
Making it hard coded would be bad, as we had more limited items now. It should be based on airtable field

**Comment by Gitstar-OC** [comment]
I forgot there is a out of stock option already being added. 

![Image](https://github.com/user-attachments/assets/4ac851b5-97c3-4a8e-a9f7-c5fc0a3b71b9) 

and the shop is also showing it now 

![Image](https://github.com/user-attachments/assets/c7971e2d-3da3-4961-a43d-c87ef4fc8a4e)

I think you updated it from the db side.
