### ISSUE TITLE
Inconsistent estimated hours for iPad

### ISSUE THREAD

**Issue by CBerJun** [hackclub/high-seas#953]
On [main page](https://highseas.hackclub.com/) the estimated hours for iPad is 87-435 hrs while in shop it says 77-387 hrs. BTW I suppose the hours on main page is correct as that is consistent in terms of the "doubloons/hr" rate with other items.

**Comment by Gitstar-OC** [comment]
Yeah, I will fix that up don't worry.

**Comment by CBerJun** [comment]
I don't think this is something you can fix in this repo though, as the data that needs to be fixed is fetched from the database.

**Comment by CBerJun** [comment]
Please be careful... I think #991 fixed the wrong thing. The 87-435 hrs is correct and it's the data in the shop page that needs to be changed. (If 1000 doubloons = 42-208 hrs, 265 doubloons = 11-54 hrs, then 2090 doubloons = 87-435 hrs is more reasonable than 77-387 hrs) cc @taciturnaxolotl

**Comment by taciturnaxolotl** [comment]
oh hrm; i'll ask nora if thats correct
