### ISSUE TITLE
The Flag Project is storing the text used for previously flagged ship.

### ISSUE THREAD

**Issue by Gitstar-OC** [hackclub/high-seas#965]
I have flagged a project before this ship and this ship shows the same description when I am going to flag another ship after the voting has been done. 

![Image](https://github.com/user-attachments/assets/0d918ab4-f7cc-468f-8ead-711fd39120a0)

**You can test it this way**
- Go to wonderdome and flag a ship
- Write something about it and then submit it
- After you have voted see another ship and click on flag you will see the same description. 

I don't know if the thing I have written is getting to the db, could someone check this up ?

**Comment by Gitstar-OC** [comment]
The same thing happened up again, 
This was the text I used for the previous ship for flagging. 

![Image](https://github.com/user-attachments/assets/8d57d27d-83a0-4a7e-a1a6-0ca7f0d35a55)

**Comment by Gitstar-OC** [comment]
I also think some flags were sent more than 1 time, could someone please check that.

**Comment by BudzioT** [comment]
Things you written are getting to db and it seems like double request are really sent and saved (double checked as I was half awake in the morning lol)

**Comment by BudzioT** [comment]
Both fixed by #973

**Comment by BudzioT** [comment]
Fixed by #973

**Comment by Gitstar-OC** [comment]
Hey don't close this issue before the pr is merged, Max told me not to do this as it confuses reviewer. Look at #854 and writing fixes / closes in the commit or description will autoclose this issue. 

Opening agian till it get's merged. Good Work : )

**Comment by BudzioT** [comment]
Closed now ; p

**Comment by BudzioT** [comment]
Now fixed ; p
