### ISSUE TITLE
Ships with less than 1 hours of update time can still be shipped.

### ISSUE THREAD

**Issue by Gitstar-OC** [hackclub/high-seas#968]
![Image](https://github.com/user-attachments/assets/fdd07bb1-c2b3-447e-8953-261db8c98865)

**Comment by BudzioT** [comment]
Doesn't seem to be occuring now? If you see this issue again, feel free to reopen

**Comment by Gitstar-OC** [comment]
Well, I can still stage my ship there is something wrong. Should I ship it and then reopen the issue ? 

![Image](https://github.com/user-attachments/assets/b0f0797c-479b-46fb-af41-86235ac9d315)

**Comment by BudzioT** [comment]
Staging is fine, shipping isn't

**Comment by BudzioT** [comment]
Nvm - you can ship old staged ships with < hour, but can't add new ships. Yours is already in db, we don't need to fix that, as people won't ship them now

**Comment by BudzioT** [comment]
I will debug it later if it still occurs

**Comment by Gitstar-OC** [comment]
Yep it is not possible! https://github.com/user-attachments/assets/151061e4-2a71-49e5-b206-6b28eade2e1a
