### ISSUE TITLE
Incorrect links for updates + allowing updates on ships before going through 10 matchups

### ISSUE THREAD

**Issue by BudzioT** [hackclub/high-seas#975]
**Incorrect links for updates**
Some people have been reporting this, but now it just blessed me, with why it can be true.
Are we taking deploy/screenshot link from root? Or updating only root ship and taking demo from the newer iteration when editing a ship? Cause people get old demos/screenshots for updates

**Wrong updates**
It seems like if ship has at least one update, people can ship an update before ship goes through 10 matchups, making the update before stuck forever without payout (as reshipped_to is set and it doesn't appear in matchups)

**Comment by BudzioT** [comment]
I think this is sort of @malted mission

**Comment by polytroper** [comment]
Assigning to @malted but @BudzioT if you are feeling hungry feel free to unassign him and wolf this down yourself

**Comment by BudzioT** [comment]
This should fix it, works on basic tests, but feel free to test it more
