### ISSUE TITLE
after screen shake it breaks size

### ISSUE THREAD

**Issue by NeonGamerBot-QK** [hackclub/high-seas#984]
from #983 
![Image](https://github.com/user-attachments/assets/79c1f786-6cb1-4be5-a90e-10befa1473e7)

**Comment by Gitstar-OC** [comment]
Yes, here for the same issue.. 

https://github.com/user-attachments/assets/6587eefc-1dee-47a7-a5b6-d7fe0f9b5f05

**Comment by Gitstar-OC** [comment]
@malted along with this after shuffling no navbar link is working you can try it. I am doing a pr to revert this and don't worry I will fix it today and update the final pr.

**Comment by Gitstar-OC** [comment]
Closing for now as the pr is reverted!
